# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: make install

    - name: Run application
      run: |
        nohup make run &
        sleep 20

    - name: Check server response
      run: |
        curl -f http://localhost:3000 || exit 1

    - name: Test search functionality
      run: |
        # Send a search query and check the server's response
        response=$(curl -X POST -d "query=machine learning" -H "Content-Type: application/x-www-form-urlencoded" http://localhost:3000/search)
        
        # Validate the response contains 5 documents and 5 similarity scores
        echo $response | jq '.documents | length == 5' || exit 1
        echo $response | jq '.similarities | length == 5' || exit 1
    

